addSettingsPanel("Personality Settings");
addSettingsPanel("Sub");
addSettingsPanel("Domme");
addSettingsPanel("Toys");
addSettingsPanel("Stroking Settings");
addSettingsPanel("Options");
addSettingsPanel("Debug Settings");
run("chatutils.js");
setUpChat();
run("personalityutils.js");
setUpGUI();
run("strokingmethodutils.js");
setUpStrokingMethods();